[contact]
sectionname = "Contact Information"
name = "Anthony J. Clark"
address1 = """
Pomona College
Computer Science
333 N. College Way
Claremont, CA 91711"""
address2 = """
<div id="email-insert"></div>
<a href="http://anthonyjclark.com">anthonyjclark.com</a>
Edmunds Hall 127
<div id="phone-insert"></div>
"""
