[contact]
sectionname = "Contact Information"
name = "Anthony J. Clark"
address1 = """
Missouri State University
Computer Science
901 S. National Ave.
Springfield, MO 65897"""
address2 = """
<div id="email-insert"></div>
<a href="http://anthonyjclark.com">anthonyjclark.com</a>
Cheek Hall, Room 307
<div id="phone-insert"></div>
"""
