[proservice]
sectionname = "Professional Activities"

[[proservice.items]]
title = "Reviewer for Journals"
details = """
Applied Sciences
Elsevier Robotics and Autonomous Systems
IEEE Transactions on Systems, Man and Cybernetics: Systems
IEEE Transactions on Robotics
Sage Adaptive Behavior
Sage International Journal of Advanced Robotic Systems"""

[[proservice.items]]
title = "Professional Society Memberships"
details = "IEEE and ACM"

[[proservice.items]]
title = "NSF Panelist"
details = """
Smart and Autonomous Systems
National Robotics Initiative
IIS Robust Intelligence"""

[[proservice.items]]
title = "Task Force Member"
date = "2018-01-01 to 2021-01-01"
organization = "IEEE Task Force on Evolutionary Developmental Systems and Robotics"

[[proservice.items]]
title = "Program Committee Member"
date = "2022-04-20"
organization = "EvoStar Conference"
location = "Brno, Czech Republic"

[[proservice.items]]
title = "Program Committee Member"
date = "2021-12-05"
organization = "IEEE Symposium Series on Computational Intelligence"
location = "(Remote) Orlando, Florida, USA"

[[proservice.items]]
title = "Reviewer"
date = "2021-04-01"
organization = "EvoApps, International Conference on the Applications of Evolutionary Computation"
location = "Seville, Spain"

[[proservice.items]]
title = "Reviewer"
date = "2021-12-01"
organization = "IEEE Symposium Series on Computational Intelligence"
location = "Orlando, Florida, USA"

[[proservice.items]]
title = "Reviewer"
date = "2020-12-01"
organization = "IEEE Symposium Series on Computational Intelligence"
location = "Canberra, Australia"

[[proservice.items]]
title = "Program Committee Member"
date = "2020-04-15"
organization = "EvoApps, International Conference on the Applications of Evolutionary Computation"
location = "Seville, Spain"

[[proservice.items]]
title = "Program Committee Member"
date = "2018-04-04"
organization = "EvoROBOT, European Conference on the Applications of Evolutionary Computation"
location = "Parma, Italy"

[[proservice.items]]
title = "Abstract and Poster"
date = "2017-09-24"
organization = "IEEE/RSJ International Conference on Intelligent Robots and Systems"
details = """
Evo-ROS: Integrating Evolutionary Robotics and ROS
Moore, Jared M., Clark, Anthony J., Simon, Glen, McKinley, Philip K. In *2017 IEEE/RSJ International Conference on Intelligent Robots and Systems*. Vancouver, BC, Canada, September, 2017"""

[[proservice.items]]
title = "Workshop Organizer, SimER: Simulation in Evolutionary Robotics Workshop"
date = "2017-07-20"
organization = "Genetic and Evolutionary Computation Conference"
location = "Berlin, Germany"
details = "Responsibilities: Co-organize a workshop that brought together experts from around the world to discuss the topic of simulation; specifically how we can improve the current state of simulation in ER."

[[proservice.items]]
title = "Reviewer"
date = "2014-12-01"
organization = "IEEE Symposium Series on Computational Intelligence"
location = "Orlando, Florida, USA"

[[proservice.items]]
title = "Reviewer"
date = "2014-09-01"
organization = "IEEE International Conference on Self-Adaptive and Self-Organizing Systems"
location = "London, UK"

[[proservice.items]]
title = "Invited Conference Talk: Evolving Aquatic Robots"
date = "2013-09-15"
details = """
The Twelfth European Conference on Artificial Life (ECAL), International Evolution of Physical Systems Workshop (EPS)
Taormina, Italy, September 2013"""

[[proservice.items]]
title = "Reviewer"
date = "2013-09-01"
organization = "IEEE International Conference on Self-Adaptive and Self-Organizing Systems"
location = "Philadelphia, Pennsylvania, USA"
